#!/bin/sh
APPDIR=`dirname $0`;
java  -cp "$APPDIR/src:$APPDIR/bin:/home/olivier/tmp/gwt-linux-1.4.61/gwt-user.jar:/home/olivier/tmp/gwt-linux-1.4.61/gwt-dev-linux.jar" com.google.gwt.dev.GWTCompiler -out "$APPDIR/www" "$@" com.teardrop.WebInterface;
